---
# Playbook: GROVER_maintain_proxy.yml
# This playbook Maintains the GROVER Application


- name: ensure hosts are setup correctly on proxy servers in yyz
  hosts: GROVER_yyz_proxy_staging, GROVER_yyz_proxy_dev, GROVER_yyz_proxy_prod


  roles:
      - { role: GROVER-common }


- name: ensure hosts are setup correctly on proxy servers in yul
  hosts: GROVER_yul_proxy_staging, GROVER_yul_proxy_dev, GROVER_yul_proxy_prod


  roles:
      - { role: GROVER-common }
